### ISSUE TITLE
Dosierung wird nicht übernommen, "Es konnte kein passendes Profil für MedicationRequest... gefunden werden."

### ISSUE THREAD

**Issue by thomasvoigt** [ere-health/ere-ps-app#44]
Hi @ManuelB,

since today a prescription line does not keep its dosage instruction data (field is blank after saving) and I cannot sign a prescription (possibly related): 
```json
[{"errors":[" Next issue ERROR - Bundle.entry[0].resource.ofType(Composition).section[0].entry[0] - Es konnte kein passendes Profil für MedicationRequest/40abb319-f677-4f76-a069-f48af282f41c unter den Auswahlmöglichkeiten [https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Prescription%7C1.0.1] gefunden werden"," Next issue INFORMATION - Bundle.entry[0].resource.ofType(Composition).section[0].entry[0] - Details für MedicationRequest/40abb319-f677-4f76-a069-f48af282f41c Abgleich gegen Profilhttps://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Prescription%7C1.0.1"," Next issue ERROR - Bundle.entry[1].resource.ofType(MedicationRequest).dosageInstruction[0].text - @value kann nicht leer sein"," Next issue ERROR - Bundle.entry[1].resource.ofType(MedicationRequest).dosageInstruction[0].text - ele-1: 'All FHIR elements must have a @value or children' Rule 'All FHIR elements must have a @value or children' Failed"],"valid":false},{"errors":[" Next issue ERROR - Bundle.entry[1].resource.ofType(MedicationRequest).dosageInstruction[0].text - @value kann nicht leer sein"," Next issue ERROR - Bundle.entry[1].resource.ofType(MedicationRequest).dosageInstruction[0].text - ele-1: 'All FHIR elements must have a @value or children' Rule 'All FHIR elements must have a @value or children' Failed"," Next issue ERROR - Bundle.entry[1].resource.section[1].entry[1].reference - \"MedicationRequest/40abb319-f677-4f76-a069-f48af282f41c\" konnte nicht in bundle (Section Entry) gefunden werden"],"valid":false}]
```

...and the patient's status cannot keep value 1 "Mitglied", default is now "0".

Thanks and best regards,
Thomas

**Comment by ManuelB** [comment]
Both should be fixed now.

**Comment by JanHanckel** [comment]
We tried it:
- patient status works

Dosage is still not applied to the prescription line

**Comment by ManuelB** [comment]
@JanHanckel can you try to reload without cache?

**Comment by ManuelB** [comment]
```
git submodule update
```
might also help. I just double checked and it works for me:
![Bildschirmfoto von 2021-09-22 15-11-40](https://user-images.githubusercontent.com/457641/134349905-b8b9ec49-d235-493c-baa2-dda4b74c69a6.png)

![Bildschirmfoto von 2021-09-22 15-11-25](https://user-images.githubusercontent.com/457641/134349910-0842f1dc-12f5-4da7-9e1b-73c48886e5ec.png)

**Comment by thomasvoigt** [comment]
Seems that there is something broken inside the git repo: We cannot update the submodules, `git submodule update` fails with 
```bash
$ git submodule update
fatal: remote error: upload-pack: not our ref 3bef30f89c1f8c288ba8732e1d7b72068f3a4177
fatal: Fetched in submodule path 'src/main/resources/META-INF/resources/frontend', but it did not contain 3bef30f89c1f8c288ba8732e1d7b72068f3a4177. Direct fetching of that commit failed.
```

Even after a checkout into a new folder, `git submodule update` fails.

**Comment by ManuelB** [comment]
@thomasvoigt this was my mistake. I forgot to update the frontend submodule. Please do the following again:

```
git pull
git submodule update
```

**Comment by thomasvoigt** [comment]
Works now,
thank you!
